# Generated by Django 4.1.7 on 2023-04-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "newspage",
                    models.CharField(
                        choices=[("1", "Sport"), ("2", "Education"), ("3", "Politics")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("newsthumbnail", models.ImageField(upload_to="images")),
                ("newstitle", models.CharField(max_length=250)),
                ("newspara1", models.TextField(max_length=800)),
                ("newspara2", models.TextField(max_length=800)),
                ("newstime", models.DateTimeField()),
                ("newsauthor", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(default="draft", editable=False, max_length=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="edittor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eitName", models.CharField(max_length=200)),
                ("eitPassword", models.CharField(max_length=140)),
                (
                    "accPage",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Sport"), ("2", "Education"), ("3", "politics")],
                        max_length=32,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="herosection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bignewsimage", models.ImageField(upload_to="images")),
                ("bignewshedding", models.CharField(max_length=300)),
                ("bignewspara1", models.TextField(max_length=800)),
                ("bignewspara2", models.TextField(max_length=800)),
                ("sidecard1image", models.ImageField(upload_to="images")),
                ("sidecard1hedding", models.CharField(max_length=300)),
                ("sidecard1para1", models.TextField(max_length=800)),
                ("sidecard1para2", models.TextField(max_length=800)),
                ("sidecard2image", models.ImageField(upload_to="images")),
                ("sidecard2hedding", models.CharField(max_length=300)),
                ("sidecard2para1", models.TextField(max_length=800)),
                ("sidecard2para2", models.TextField(max_length=800)),
                ("heroad", models.ImageField(upload_to="images")),
                ("newstime", models.DateTimeField()),
                ("newsauthor", models.CharField(max_length=200)),
            ],
        ),
    ]
