# Generated by Django 4.1.7 on 2023-03-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="status",
            field=models.CharField(default="draft", max_length=15),
        ),
    ]
