# Generated by Django 4.1.7 on 2023-04-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="herosectionnews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sidecard1image", models.ImageField(upload_to="images")),
                ("sidecard1hedding", models.CharField(max_length=300)),
                ("sidecard1para1", models.TextField(max_length=800)),
                ("sidecard1para2", models.TextField(max_length=800)),
                ("sidecard2image", models.ImageField(upload_to="images")),
                ("sidecard2hedding", models.CharField(max_length=300)),
                ("sidecard2para1", models.TextField(max_length=800)),
                ("sidecard2para2", models.TextField(max_length=800)),
            ],
        ),
        migrations.RemoveField(model_name="herosection", name="sidecard1hedding",),
        migrations.RemoveField(model_name="herosection", name="sidecard1image",),
        migrations.RemoveField(model_name="herosection", name="sidecard1para1",),
        migrations.RemoveField(model_name="herosection", name="sidecard1para2",),
        migrations.RemoveField(model_name="herosection", name="sidecard2hedding",),
        migrations.RemoveField(model_name="herosection", name="sidecard2image",),
        migrations.RemoveField(model_name="herosection", name="sidecard2para1",),
        migrations.RemoveField(model_name="herosection", name="sidecard2para2",),
    ]
