# Generated by Django 4.1.7 on 2023-03-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edittor",
            name="accPage",
            field=models.CharField(
                blank=True,
                choices=[("1", "Sport"), ("2", "Education"), ("3", "politics")],
                max_length=32,
                null=True,
            ),
        ),
    ]
