# Generated by Django 4.1.7 on 2023-03-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0002_alter_draft_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="newspage",
            field=models.CharField(
                choices=[("1", "Sport"), ("2", "Education"), ("3", "Politics")],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="draft",
            name="newspara1",
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name="draft",
            name="newspara2",
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name="draft",
            name="status",
            field=models.CharField(default="draft", editable=False, max_length=15),
        ),
    ]
