# Generated by Django 4.1.7 on 2023-04-01 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0003_remove_herosectionnews_sidecard2hedding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosectionnews",
            name="newsauthor",
            field=models.CharField(default="SP News", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="herosectionnews",
            name="newstime",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
